src/graphics/shader/Makefile.am
src/graphics/shader/shadermaterial.cpp
src/graphics/shader/shadermaterial.h

This adds ShaderMaterial, a class for a managed approach to
fragment shader variables. This includes automatic
calculation of texture units to use for shader samplers.

GRAPHICS: Add ShaderMaterial class

---

src/graphics/mesh/mesh.cpp

The mesh init call is fully enabled, allowing GL resource
allocation and mesh rendering.

GRAPHICS: Enable mesh initialisation

---

src/graphics/aurora/texture.cpp
src/graphics/aurora/texture.h
src/graphics/texture.cpp
src/graphics/texture.h

Interfaces necessary for OpenGL promoted to the texture base class.
The reasoning behind this is to allow shader samplers to reference
a texture directly instead of only relying on the OpenGL handle.
This easily allows the texture to be reloaded without needing to
synchronise any ShaderMaterial that might be using the texture.

GRAPHICS: Texture base class _textureID

---

src/graphics/shader/shader.cpp
src/graphics/shader/shader.h
src/graphics/shader/shadermaterial.cpp
src/graphics/shader/shadermaterial.h

ShaderSampler directly points to a texture object, allowing the
GL handler id to be accessed without any kind of synchronisation.
This also means no special "ShaderMaterialSampler" is required.

GRAPHICS: ShaderSampler direct texture pointer

---

src/graphics/mesh/mesh.cpp
src/graphics/mesh/mesh.h

Mesh rendering can be performed separate to actual binding. This
allows multiple render calls without rebinding the same data, which
would otherwise be a waste of GL calls.

GRAPHICS: Mesh bind and render separation

---

src/graphics/shader/Makefile.am
src/graphics/shader/shaderrenderable.cpp
src/graphics/shader/shaderrenderable.h

ShaderRenderable is a wrapper class around a material, surface,
and mesh. It will automatically track a pointer to the shader
program for the provided material and surface.

GRAPHICS: Shader renderable

---

src/graphics/shader/shadercode.cpp

OpenGL 2.1 should use #version 120 for shaders. As an older GLSL
version, float precision is not required.

GRAPHICS: Shader version 120

---

src/graphics/aurora/cursor.cpp

I recognized a bug in the graphics system which caused it to crash when loading a compressed cursor image on a non-s3tc system. I added some lines to make the cursor image decompress on such systems.

GRAPHICS: Fix a bug with missing S3TC decompression on cursors

---

src/engines/kotor/gui/widgets/button.cpp
src/engines/kotor/gui/widgets/button.h

As I have written in my Character Generation Menu pull request, there was a bug, making the button texts disappear. I have now fixed this in this commit.

KOTOR: Fix for button text disappearing in character menu

---

.appveyor.yml

Looks like NASM is now a 64bit application, installed in "Program Files" folder.

BUILD: Update NASM path for AppveyorCI builds

---

cmake/FindSDL2.cmake

Because the cmake script was not able to see the correct path for the mac ports version of sdl2 i created another hint to point it there.

BUILD: Add a path hint for recognizing macports version of sdl2

---

src/graphics/aurora/subscenequad.cpp
src/graphics/aurora/subscenequad.h

I tried to get parts of the character generation subscenes to animate until I realized, that the subscene is not giving timestamps to the renderables, so i added this in this PR.

GRAPHICS: Add time handling to subscene quads

---

src/engines/kotor/gui/widgets/kotorwidget.cpp
src/engines/nwn/gui/main/newmodule.cpp
src/engines/nwn/gui/main/newpremium.cpp
src/engines/nwn/gui/widgets/listbox.cpp
src/engines/nwn/gui/widgets/textwidget.cpp
src/engines/nwn/gui/widgets/textwidget.h
src/engines/sonic/game.cpp
src/graphics/aurora/highlightabletext.cpp
src/graphics/aurora/highlightabletext.h
src/graphics/aurora/text.cpp
src/graphics/aurora/text.h
src/graphics/aurora/types.h
src/graphics/font.cpp
src/graphics/font.h

To make text layouting possible we need to give the text quad the same height and width as the underlaying widget quad. Layouting is done by defining a writing direction (ltr,rtl) and a block direction (these come later and are defined by the display language) and then aligning the text in the text quad according to vertical and horizontal alignment.
This PR
* renames the existing align to horizontal align
* add a vertical align
* defines common values for vertical and horizontal align
* adds a Text constructor with width and height parameters added

Base work for text rendering changes

---

src/engines/aurora/loadprogress.cpp
src/graphics/aurora/fps.cpp
src/graphics/aurora/fps.h
src/graphics/aurora/text.cpp
src/graphics/aurora/text.h

This is the 2nd part of the changes to layout text according to alignment.
This PR has the actual changes to the layout algorithm.
The changes to the FPS and LoadProgress classes are showcases that were simple to implement.
There should be no regressions to any Text drawing not using the new constructor introduced in part 1.
To test out these changes the FPS class uses the whole xoreos window for layouting.
Using different alignment values than the default (Upper Left) should put the text in another part of the screen.

Textrender2

---

src/engines/kotor/creature.cpp
src/engines/kotor/gui/chargen/chargeninfo.cpp

Scout and scoundrel body models were mixed up.

KOTOR: Fix class body model names

---

src/engines/kotor/creature.cpp

This PR adds the loading of the creature  gender from gff.

KOTOR: Read creatures gender on loading it

---

src/engines/kotor/creature.cpp

After #212 I searched for the cause of the error and found out, that the Subrace field is actually a string field and is not used, even on wookies. I found out, that there is a second field called "SubraceIndex" which contains the actual subrace information.

KOTOR: Fix subrace loading bug

---

src/engines/kotor/gui/main/options.cpp
src/engines/kotor/gui/options/autopause.cpp
src/engines/kotor/gui/options/feedback.cpp
src/engines/kotor/gui/options/gameplay.cpp
src/engines/kotor/gui/options/graphics.cpp
src/engines/kotor/gui/options/graphicsadv.cpp
src/engines/kotor/gui/options/keyboardconfig.cpp
src/engines/kotor/gui/options/mousesettings.cpp
src/engines/kotor/gui/options/sound.cpp
src/engines/kotor/gui/options/soundadv.cpp

After I recognized that the background for the options menu is missing, i added it.

KOTOR: Add the background for options menus

---

src/engines/aurora/gui.cpp
src/engines/kotor/area.cpp
src/engines/kotor/gui/ingame/container.cpp
src/engines/kotor/gui/ingame/container.h
src/engines/kotor/gui/ingame/hud.cpp
src/engines/kotor/gui/ingame/hud.h
src/engines/kotor/gui/ingame/ingame.cpp
src/engines/kotor/gui/ingame/ingame.h
src/engines/kotor/gui/ingame/rules.mk
src/engines/kotor/module.cpp
src/engines/kotor/module.h
src/engines/kotor/placeable.cpp
src/engines/kotor/placeable.h

This commit tries to bridge between the selection of objects and the handling of module specific stuff, in this case, when the player clicks on a chest, the ingame ui will open a window for managing the contents of the container.

KOTOR: Container menu

---

src/engines/kotor/module.cpp

fix the loading of maps which have no '_'Ä character, like the dantooine and manaan maps.

ENGINES: Fix the loading of minimaps without a _

---

tests/googletest/src/gtest_main.cc

Otherwise main gets replaced with SDL_main which leads to tests
compilation errors on Windows

TESTS: Undefine SDL main macro for Google Test

---

src/common/deflate.cpp
src/common/deflate.h
tests/common/deflate.cpp

This PR adds the possibility to decompress zlib data wihout knowing the exact size.

COMMON: Deflate without knowing the output size

---

.appveyor.yml
src/sound/decoders/mp3.cpp

Hi, as the title says, this should fix the builds on Appveyor.
The dependencies are now pulled using `vcpkg` because it will probably do a better job at building these third party libraries on Windows and because it's available out of the box on Appveyor.
Also `libxvid` and `libfaad` aren't provided by `vcpkg` but if anyone wants to send https://github.com/Microsoft/vcpkg a PR with the corresponding port, they will probably be happy to integrate them.
Then there's a link error because of some global const variable in `libmad` not declared extern in `libmad` sources, so it's treated as a static. I have no clue why this was working before, maybe a different `libmad` version or compilation flags between what `xoreos` was doing and what `vcpkg` does. Anyway, i didn't really see the point of …

Fix appveyor builds, use vcpkg to install dependencies on Windows

---

src/engines/kotor/creature.cpp
src/engines/kotor/creature.h
src/engines/kotor/module.cpp
src/engines/kotor2/creature.cpp
src/engines/kotor2/creature.h
src/engines/kotor2/module.cpp
src/engines/nwn/module.cpp
src/graphics/aurora/animation.cpp
src/graphics/aurora/animation.h
src/graphics/aurora/animationthread.cpp
src/graphics/aurora/animationthread.h
src/graphics/aurora/model.cpp
src/graphics/aurora/model.h
src/graphics/aurora/model_kotor.cpp
src/graphics/aurora/model_nwn.cpp
src/graphics/aurora/modelnode.cpp
src/graphics/aurora/modelnode.h
src/graphics/aurora/rules.mk
src/graphics/graphics.cpp
src/graphics/graphics.h

This PR adds a dedicated animation thread for all supported games. Currently NWN, KotOR and KotOR II are enabled to use it. Using a separate thread drastically improves performance when every creature in a module is animated. To disable it use --animthread=0 on the command line.

GRAPHICS: Add dedicated animation thread

---

src/engines/jade/module.cpp

We shut down otherwise.
```
ERROR: Failed loading module "j01_town"
Because: Failed to index mandatory archive "j01_town/a010.rim"
Because: Archive "/Users/charlotte/Documents/jadehacking/data/app/data/j01_town/a010.rim" already opened
Shutting down
Cleaning up shaders...
```

JADE: Don't attempt to loadmodule() the current module

---

src/engines/aurora/kotorjadegui/kotorinventoryitem.cpp
src/engines/aurora/kotorjadegui/kotorjadewidget.cpp
src/engines/aurora/kotorjadegui/label.cpp
src/engines/aurora/kotorjadegui/label.h
src/engines/aurora/kotorjadegui/listbox.cpp
src/engines/kotor/console.cpp
src/engines/kotor/console.h
src/engines/kotor/creature.cpp
src/engines/kotor/creature.h
src/engines/kotor/gui/ingame/container.cpp
src/engines/kotor/gui/ingame/hud.cpp
src/engines/kotor/gui/ingame/hud.h
src/engines/kotor/gui/ingame/menu.cpp
src/engines/kotor/gui/ingame/menu_equ.cpp
src/engines/kotor/gui/ingame/menu_equ.h
src/engines/kotor/inventory.cpp
src/engines/kotor/inventory.h
src/engines/kotor/item.cpp
src/engines/kotor/item.h
src/engines/kotor/module.cpp
src/engines/kotor/module.h
src/engines/kotor/types.h
src/graphics/aurora/model.cpp

This PR:
1. Adds console command to modify inventory of creatures and placeables.
2. Partly implements equipment screen functionality: equipment slot selection, party inventory display, fixation on equipment slot.

KotOR equipment screen update

---

src/engines/kotor/gui/ingame/hud.cpp

This PR adds the ability to scale the hud of no proper resolution is found.

KOTOR: HUD Scaling

---

src/engines/jade/jade.cpp

This PR should fix the encoding of jade to utf8. Since it was configured with the wrong encodings.

JADE: Fix a language encoding problem

---

src/aurora/rules.mk
src/aurora/sacfile.cpp
src/aurora/sacfile.h

This PR adds support for sac files. These are essentially gff3 files with an extra header, used in Jade Empire as save files.

AURORA: SACFile

---

src/engines/aurora/kotorjadegui/kotorjadewidget.cpp
src/engines/kotor/gui/main/main.cpp
src/engines/kotor/gui/main/main.h
src/graphics/aurora/subscenequad.cpp
src/graphics/aurora/subscenequad.h

This PR adds the malak model standing in the main menu

KOTOR: Main menu model

---

src/engines/kotor/script/functions_global.cpp

I recognized a small bug in the setGlobalBoolean nwscript function.

KOTOR: Fix the wrong function in setGlobalBoolean

---

src/aurora/actionscript/array.cpp

This fixes compilation error on VS 2017

AURORA: Fix return value of Array::getMember

---

m4/boost.m4

BUILD: Ensure that -DBOOST_UUID_RANDOM_PROVIDER_FORCE_WINCRYPT is used by boost.m4

---

src/engines/kotor/gui/guibackground.cpp

This fills the remaining background of guis with background with black.

KOTOR: Fill remaining gui background with black

---

src/aurora/gfxfile.cpp
src/aurora/gfxfile.h
src/aurora/rules.mk

As the name says, this PR introduces a loader for scaleform gfx files, used by dragonage and dragonage2. I still does not implement all of the necessary tags, but the most relevant ones.

AURORA: Add loader for Scaleform GFx files

---

src/aurora/pefile.cpp

A small fix which fixes the remapping of cursors, which led to wrong cursors being shown in kotor.

AURORA: Fix PEFile cursor remap

---

src/engines/nwn2/game.cpp
src/engines/nwn2/game.h
src/engines/nwn2/nwn2.cpp
src/engines/nwn2/nwn2.h
src/engines/nwn2/script/function_tables.h
src/engines/nwn2/script/functions.cpp
src/engines/nwn2/script/functions.h

This will remove a warning during startup about a TODO function. The code sets
the default difficulty value to '2' for the GAME_DIFFICULTY_NORMAL mode and
checks that the difficulty value is in the range 0 (GAME_DIFFICULTY_VERY EASY)
to 4 (GAME_DIFFICULTY_DIFFICULT).

NWN2: Add GetGameDifficulty() script function

---

src/graphics/aurora/modelnode.cpp

Properly assign texture index 2 to a generated ShaderMaterial, if
that index will be required.

GRAPHICS: Fix texture index 2 assignment to material

---

src/graphics/aurora/modelnode.cpp

Correctly apply deg2rad for render transform calculation when using
GLM and shader based rendering.

GRAPHICS: GLM takes rotation in radians

---

.appveyor.yml

Second attempt, without the test commits. I hadn't realised that the cache isn't updated when building pull requests. Hopefully fixes issue #428

APPVEYOR: Add the path for NASM to the cache

---

src/engines/kotor/gui/ingame/hud.cpp
src/engines/kotor/gui/ingame/hud.h
src/engines/kotor/gui/ingame/ingame.cpp
src/engines/kotor/gui/ingame/ingame.h
src/engines/kotor/gui/ingame/selectioncircle.cpp
src/engines/kotor/gui/ingame/selectioncircle.h
src/engines/kotor2/gui/ingame/ingame.cpp
src/engines/kotor2/gui/ingame/ingame.h
src/engines/kotorbase/gui/ingame.h
src/engines/kotorbase/module.cpp
src/engines/kotorbase/module.h
src/engines/kotorbase/object.cpp
src/engines/kotorbase/object.h
src/engines/kotorbase/objectcontainer.h
src/engines/kotorbase/situated.cpp
src/engines/kotorbase/situated.h

This PR updates selection mechanics in KotOR to match the original games. We now have two selection circles: persistant one for the current target and temporary one for the hovered object. In order to use the object, you have to target it first. Also, locked situated objects will now have (empty) target buttons above them.
Known issues:
- Cursor should only change on hover when the object is targeted
- Selection circles only work for situated objects currently (but creatures still need to be targeted prior to activation)
Note: Should probably port that to KotOR 2 as well.

ENGINES: Update selection mechanics to match KotOR games

---

src/engines/kotor/gui/ingame/hud.cpp
src/engines/kotorbase/actionexecutor.cpp
src/engines/kotorbase/actionexecutor.h
src/engines/kotorbase/area.cpp
src/engines/kotorbase/door.cpp
src/engines/kotorbase/door.h
src/engines/kotorbase/gui/hud.cpp
src/engines/kotorbase/gui/hud.h
src/engines/kotorbase/module.cpp
src/engines/kotorbase/module.h
src/engines/kotorbase/partycontroller.cpp
src/engines/kotorbase/placeable.cpp
src/engines/kotorbase/placeable.h
src/engines/kotorbase/situated.cpp
src/engines/kotorbase/situated.h

- Object click is first handled in Module, then in Area (this fixes premature door activation)
- Make doors not usable when opened
- Hide selection when entering menus or unloading the module

ENGINES: Implement OpenLock action execution, fixes, HUD refactoring

---

src/engines/kotorbase/actionexecutor.cpp
src/engines/kotorbase/actionexecutor.h
src/engines/kotorbase/area.cpp
src/engines/kotorbase/creature.cpp
src/engines/kotorbase/gui/hud.cpp
src/engines/kotorbase/gui/selectioncircle.cpp
src/engines/kotorbase/gui/selectioncircle.h
src/engines/kotorbase/module.cpp
src/engines/kotorbase/module.h
src/engines/kotorbase/partyleader.cpp
src/engines/kotorbase/script/functions_action.cpp

- Fix #480 as suggested
- Issue a "use object" action on click, like in original games (partially solves #479, but still)
- Use ExecutionContext structure in ActionExecutor

KOTOR: Fix selection, use object action, actions refactoring

---

src/engines/odyssey/button.cpp

A small fix to adjust the lock icon in both kotor games like it is in the original

ODYSSEY: Adjust icon to be in the middle of the widget

---

src/rules.mk

Otherwise, the MinGW build fails because of the `config.h` file not being
found.

BUILD: Add build folder to the include path for win32/xoreos.rc

---

src/aurora/erffile.cpp
src/aurora/erffile.h
src/common/lzma.cpp
src/common/lzma.h
src/common/readstream.h

BioWare seems to have created their own (?) custom chunked LZMA format here, which at least seems minimal on top of LZMA1. This parses through that.
DA2 PS3 gets further along now, actually able to parse the initial room before failing to load any mesh (new format?).
This should be half of #335.

AURORA: Add support for DA2 PS3 ERF LZMA decompression

---

cmake/FindSDL2.cmake

A small tweak to the FindSDL2 file so CMake can find SDL2 on Haiku without user input. By @Begasus

Make CMake find SDL2 on Haiku
