src/graphics/shader/Makefile.am
src/graphics/shader/shadersurface.cpp
src/graphics/shader/shadersurface.h

This adds ShaderSurface, a class for a managed approach to
vertex shader variables. It's similar in function to
ShaderMaterial.

GRAPHICS: Add ShaderSurface class

---

src/graphics/mesh/Makefile.am
src/graphics/mesh/mesh.cpp
src/graphics/mesh/mesh.h
src/graphics/mesh/meshman.cpp
src/graphics/mesh/meshman.h
src/graphics/shader/Makefile.am
src/graphics/shader/materialman.cpp
src/graphics/shader/materialman.h
src/graphics/shader/shadermaterial.cpp
src/graphics/shader/shadermaterial.h
src/graphics/shader/shadersurface.cpp
src/graphics/shader/shadersurface.h
src/graphics/shader/surfaceman.cpp
src/graphics/shader/surfaceman.h

Some commits gathered together here for basic resource management. Nothing is yet actually called, however this is the last of the foundations before starting to switch over to shader based rendering.

GRAPHICS: Resource Managers

---

CMakeLists.txt

BUILD: Add libxml2 dependency to the CMake build system

---

src/engines/kotor/script/functions_module.cpp

I recopnized that i managed to inesert a bug into the fading system of kotor while cleaning up the style issues. I have now corrected it.

KOTOR: Fix a bug with a fadein fading out

---

src/engines/kotor/gui/ingame/hud.cpp
src/engines/kotor/gui/ingame/hud.h
src/engines/kotor/gui/ingame/ingame.cpp
src/engines/kotor/gui/ingame/ingame.h
src/engines/kotor/gui/ingame/rules.mk
src/engines/kotor/gui/widgets/kotorwidget.cpp
src/engines/kotor/gui/widgets/kotorwidget.h
src/engines/kotor/module.cpp
src/engines/kotor/module.h
src/graphics/aurora/guiquad.cpp
src/graphics/aurora/guiquad.h

After solving #169 i was able to build a basic version of the ingame ui which displays all the HUD elements without doing anything else, while maintaining pickability of scene objects.

KOTOR: Basic KotOR ingame menu

---

src/common/matrix4x4.cpp
src/common/matrix4x4.h
src/graphics/aurora/animation.cpp
src/graphics/aurora/animation.h
src/graphics/aurora/model.cpp
src/graphics/aurora/model.h
src/graphics/aurora/model_kotor.cpp
src/graphics/aurora/model_kotor.h
src/graphics/aurora/model_sonic.cpp
src/graphics/aurora/modelnode.cpp
src/graphics/aurora/modelnode.h

Mostly working KotOR animations implementation. Uses CPU for skeletal animation. There are some unhandled model node controller types (namely, compressed quaternions).

GRAPHICS: Implement KotOR animations

---

src/graphics/aurora/animation.cpp
src/graphics/aurora/animation.h
src/graphics/aurora/animnode.cpp
src/graphics/aurora/animnode.h
src/graphics/aurora/model.cpp
src/graphics/aurora/model.h
src/graphics/aurora/model_nwn.cpp

Works for both KotOR and NWN.
FPS improvement on my machine (Ryzen 1600 + RX480):
KotOR (class selection) +62%
NWN (prelude, chapter 1-4) +6-16%

GRAPHICS: Cache animation nodes

---

src/engines/kotor/gui/gui.cpp
src/engines/kotor/gui/gui.h
src/engines/kotor/gui/widgets/checkbox.cpp
src/engines/kotor/gui/widgets/kotorwidget.cpp
src/engines/sonic/game.cpp
src/graphics/aurora/highlightabletext.cpp
src/graphics/aurora/highlightabletext.h

This is part 4 of the text rendering changes.
This deals with Kotor1 and Sonic.
(And to a lesser extend Jade and Kotor2)

Textrender4

---

src/engines/jade/gui/main/main.cpp
src/engines/jade/jade.cpp
src/engines/sonic/sonic.cpp
src/graphics/graphics.cpp
src/graphics/graphics.h

This is primarily for Jade.
All GUI elements are scaled to screen size.

Gui scaling

---

src/aurora/lytfile.cpp
src/aurora/lytfile.h
src/engines/jade/area.cpp
src/engines/jade/area.h
src/engines/jade/arealayout.cpp
src/engines/jade/arealayout.h
src/engines/jade/gui/main/main.cpp
src/engines/jade/gui/main/main.h
src/engines/jade/room.cpp
src/engines/jade/room.h
src/engines/jade/rules.mk
src/engines/kotor/gui/gui.cpp

This shows a background based on the game's chapter the player has currently advanced to.

Jade main menu background

---

src/engines/aurora/console.cpp
src/graphics/aurora/guiquad.cpp
src/graphics/aurora/guiquad.h
src/graphics/aurora/text.cpp
src/graphics/aurora/text.h
src/graphics/graphics.cpp
src/graphics/graphics.h
src/graphics/guielement.h
src/graphics/renderable.cpp
src/graphics/types.h

This changes the console text and quads to be no longer GUI elements.

console scaling

---

src/engines/jade/gui/main/main.cpp

Adds the credits movie to the main menu

JADE: Add credits movie to main menu

---

src/engines/kotor/script/functions_object.cpp

Correct the setMaxHitPoints nwscript exception string

KOTOR: Correct setMaxHitPoints exception string

---

src/engines/kotor/item.cpp
src/engines/kotor/item.h
src/engines/kotor/placeable.cpp
src/engines/kotor/placeable.h
src/engines/kotor/rules.mk

This PR adds a basic class representing an item in kotor and lets placeables with an inventory create it's items.

KOTOR: Items

---

src/engines/kotor2/creature.cpp
src/engines/kotor2/creature.h
src/engines/kotor2/game.cpp
src/engines/kotor2/gui/chargen/charactergeneration.cpp
src/engines/kotor2/gui/chargen/charactergeneration.h
src/engines/kotor2/gui/chargen/chargenbase.cpp
src/engines/kotor2/gui/chargen/chargenbase.h
src/engines/kotor2/gui/chargen/chargeninfo.cpp
src/engines/kotor2/gui/chargen/chargeninfo.h
src/engines/kotor2/gui/chargen/chargenname.cpp
src/engines/kotor2/gui/chargen/chargenname.h
src/engines/kotor2/gui/chargen/chargenportrait.cpp
src/engines/kotor2/gui/chargen/chargenportrait.h
src/engines/kotor2/gui/chargen/classselection.cpp
src/engines/kotor2/gui/chargen/classselection.h
src/engines/kotor2/gui/chargen/customchar.cpp
src/engines/kotor2/gui/chargen/customchar.h
src/engines/kotor2/gui/chargen/quickchar.cpp
src/engines/kotor2/gui/chargen/quickchar.h
src/engines/kotor2/gui/chargen/quickorcustom.cpp
src/engines/kotor2/gui/chargen/quickorcustom.h
src/engines/kotor2/gui/chargen/rules.mk
src/engines/kotor2/gui/main/main.cpp
src/engines/kotor2/gui/main/main.h
src/engines/kotor2/gui/widgets/button.h
src/engines/kotor2/gui/widgets/label.h
src/engines/kotor2/gui/widgets/rules.mk
src/engines/kotor2/module.cpp
src/engines/kotor2/types.h

This PR implements the kotor 2 character generation menu. It is in many cases very similar to the kotor character generation menu.

KOTOR2: Character generation menu

---

src/engines/kotor2/gui/chargen/chargeninfo.cpp

This PR should fix #240 regarding the kotor2 character generation

KOTOR2: Fix #240 for kotor2 chargen

---

src/engines/kotor2/area.cpp
src/engines/kotor2/area.h
src/engines/kotor2/console.cpp
src/engines/kotor2/console.h
src/engines/kotor2/creature.cpp
src/engines/kotor2/creature.h
src/engines/kotor2/module.cpp
src/engines/kotor2/module.h

Ported satellite camera, PC movement (w/ animations) and collision detection

Port my work from KotOR to KotOR 2

---

src/engines/kotor/gui/ingame/hud.cpp
src/engines/kotor/gui/ingame/hud.h
src/engines/kotor/gui/ingame/ingame.cpp
src/engines/kotor/gui/ingame/menu.cpp
src/engines/kotor/gui/ingame/menu.h
src/engines/kotor/gui/main/main.cpp
src/engines/kotor/gui/saveload.cpp
src/engines/kotor/gui/saveload.h
src/engines/kotor/gui/widgets/listbox.cpp
src/engines/kotor/gui/widgets/listbox.h
src/engines/kotor/module.cpp
src/engines/kotor/module.h
src/engines/kotor/rules.mk
src/engines/kotor/savedgame.cpp
src/engines/kotor/savedgame.h

Made load/save game menu scrollable using up/down arrows; implemented saved game loading (time played, current module, PC gender and position)

KotOR savegames WIP

---

AUTHORS

It's important to me, at least.
While here, update my email address

DOCS: Update Charlotte's name in contributors list

---

src/engines/kotor/creature.cpp

After I found out, how the actual skin textures are called, i replaced the pc standard outfit body with the standard no-outfit body.

KOTOR: Replaces pc appearence with the actual armorless outfit

---

src/engines/kotor/area.cpp
src/engines/kotor/area.h
src/engines/kotor/console.cpp
src/engines/kotor/console.h
src/engines/kotor/creature.cpp
src/engines/kotor/creature.h
src/engines/kotor/gui/saveload.cpp
src/engines/kotor/module.cpp
src/engines/kotor/module.h
src/engines/kotor/object.cpp
src/engines/kotor/object.h
src/engines/kotor2/area.cpp
src/engines/kotor2/area.h
src/engines/kotor2/console.cpp
src/engines/kotor2/console.h
src/engines/kotor2/creature.cpp
src/engines/kotor2/creature.h
src/engines/kotor2/module.cpp
src/engines/kotor2/module.h
src/engines/kotor2/object.cpp
src/engines/kotor2/object.h
src/graphics/aurora/animation.cpp
src/graphics/aurora/model.cpp
src/graphics/aurora/model.h
src/graphics/aurora/model_kotor.cpp
src/graphics/aurora/model_kotor.h

This PR introduces facial animations for KotOR games. Console command "playanim" could be used to test those, e.g. "playanim tlknorm talk" when a character is highlighted.

KotOR facial animations

---

src/engines/kotor/module.cpp
src/engines/kotor2/module.cpp

ENGINES: Fix segfault on module change in KotOR games

---

src/engines/kotor/creature.cpp
src/engines/kotor2/creature.cpp
src/graphics/aurora/animation.cpp
src/graphics/aurora/animation.h
src/graphics/aurora/animationchannel.cpp
src/graphics/aurora/animationchannel.h
src/graphics/aurora/model.cpp
src/graphics/aurora/model.h
src/graphics/aurora/model_kotor.cpp
src/graphics/aurora/model_nwn.cpp
src/graphics/aurora/modelnode.h
src/graphics/aurora/rules.mk

This PR fixes various animation bugs in KotOR 1/2 and adds support for multiple animations per model.

KotOR animations fix

---

src/engines/aurora/kotorjadegui/listbox.cpp
src/engines/aurora/kotorjadegui/listbox.h
src/engines/aurora/kotorjadegui/protoitem.cpp
src/engines/aurora/kotorjadegui/protoitem.h
src/engines/kotor/gui/dialog.cpp
src/engines/kotor/gui/ingame/menu_equ.cpp
src/engines/kotor/gui/saveload.cpp

All three have different combinations of item selection sounds.

KOTOR: Customize listbox sounds in saveload menu, dialogs and equipment screen

---

src/engines/aurora/kotorjadegui/checkbox.cpp
src/engines/aurora/kotorjadegui/checkbox.h
src/engines/aurora/kotorjadegui/kotorjadewidget.cpp
src/engines/kotor/gui/gui.cpp
src/engines/kotor/gui/ingame/partyselection.cpp
src/engines/kotor/module.cpp
src/engines/kotor/module.h
src/engines/kotor/partyconfig.cpp
src/engines/kotor/partyconfig.h
src/engines/kotor/rules.mk
src/engines/kotor/script/function_tables.h
src/engines/kotor/script/functions.h
src/engines/kotor/script/functions_action.cpp
src/engines/kotor/script/functions_party.cpp

Applying changes in-game are for later PR.

KOTOR: Implement party selection in party selection GUI

---

src/engines/aurora/kotorjadegui/kotorjadewidget.cpp
src/engines/aurora/kotorjadegui/kotorjadewidget.h
src/engines/kotor/gui/ingame/hud.cpp
src/engines/kotor/gui/ingame/hud.h
src/engines/kotor/gui/ingame/ingame.cpp
src/engines/kotor/gui/ingame/ingame.h
src/engines/kotor/gui/ingame/minimap.cpp
src/engines/kotor/gui/ingame/minimap.h
src/engines/kotor/module.cpp
src/graphics/aurora/guiquad.cpp
src/graphics/aurora/guiquad.h

This PR makes the arrow in the minimap spin around on the camera angle.

KOTOR: Add spinning map arrow

---

src/engines/kotor/area.cpp
src/engines/kotor/creature.cpp
src/engines/kotor/door.cpp
src/engines/kotor/gui/gui.cpp
src/engines/kotor/placeable.cpp

This PR adds some ingame cursors, which will appear, when hovering over specific objects. Also i changed the click event from a mouse down to a mouse up event since this matches more the overall behaviour of the game.

KOTOR: Some ingame cursors

---

src/engines/aurora/kotorjadegui/kotorjadewidget.cpp
src/engines/kotor/gui/ingame/hud.cpp
src/engines/kotor/gui/main/main.cpp

This PR fixes the disabled clearing in almost all subscenes since my malak mainmenu PR.

KOTOR: Fix subscene clearing

---

src/engines/kotor/module.cpp
src/engines/kotor/module.h
src/engines/kotor/script/container.cpp
src/engines/kotor/script/container.h
src/engines/kotor/script/function_tables.h
src/engines/kotor/script/functions.h
src/engines/kotor/script/functions_party.cpp
src/engines/kotor/situated.cpp

This PR fixes some things and ultimately enables to open the first door when switched to trask.

KOTOR: Party fix

---

src/engines/aurora/gui.cpp

This PR slightly modifies the process of putting a gui on a gui and therefore fixes #231.

ENGINES: Move sub gui before gui when hideSelf is false when subbing

---

src/sound/decoders/wwriffvorbis.cpp

A small fix to compile when vorbis is disabled.

SOUND: Fix vorbis usage when vorbis is not enabled

---

src/graphics/aurora/modelnode.cpp
src/graphics/aurora/modelnode.h

Fix environment maps (under and over) not being rendered.

GRAPHICS: Fix environment map rendering

---

src/engines/nwn/gui/legal.cpp

Properly update fade alpha when rendering legal billboard with
shader render path.

NWN: legal billboard fade with shader rendering

---

src/engines/nwn/gui/ingame/dialog.cpp
src/graphics/shader/materialman.cpp

Make dialog backdrop translucent with shader rendering.

NWN: Translucent ingame dialog with shader rendering

---

src/aurora/ltrfile.cpp
src/common/random.cpp
src/common/random.h
src/common/rules.mk
src/engines/aurora/util.cpp
src/engines/dragonage/script/functions_math.cpp
src/engines/dragonage2/script/functions_math.cpp
src/engines/jade/arealayout.cpp
src/engines/jade/script/functions.cpp
src/engines/kotor/gui/chargen/chargeninfo.cpp
src/engines/kotor2/gui/chargen/chargeninfo.cpp
src/engines/kotorbase/script/functions.cpp
src/engines/kotorbase/sound.cpp
src/engines/nwn/gui/main/newgamefog.cpp
src/engines/nwn/script/functions.cpp
src/engines/nwn2/creature.cpp
src/engines/nwn2/script/functions.cpp
src/engines/witcher/nwscript/functions.cpp
src/events/events.cpp
src/graphics/aurora/animationchannel.cpp

This PR replaces srand/rand functions with random number generation from C++11. This fixes #449.

COMMON: Use random number generation from C++11

---

src/engines/kotorbase/cameracontroller.cpp
src/engines/kotorbase/cameracontroller.h
src/engines/kotorbase/gui/hud.cpp
src/engines/kotorbase/gui/hud.h
src/engines/kotorbase/module.cpp

This PR improves the satellite camera in KotOR games by fixing the movement lag and also interpolating camera position when it hits the obstacle and returns back to normal.

KOTOR: Improve camera handling

---

src/engines/kotorbase/area.cpp
src/engines/kotorbase/area.h
src/engines/kotorbase/door.cpp
src/engines/kotorbase/door.h
src/engines/kotorbase/object.cpp
src/engines/kotorbase/object.h
src/engines/kotorbase/trigger.cpp
src/engines/kotorbase/trigger.h
src/engines/nwn2/trigger.cpp
src/engines/nwn2/trigger.h
src/engines/odyssey/button.cpp
src/engines/odyssey/widget.cpp

Also use set for visible rooms instead of a vector.

KOTOR: Fix room visibility not being evaluated on start

---

src/engines/kotor2/creature.cpp
src/engines/kotorbase/actionexecutor.cpp

Also fix certain head missing in KotOR 2.

 KOTOR: Fix regression in interaction with placeables

---

src/common/platform.cpp

`VerSetConditionMask` and `VerifyVersionInfo` are unavailable prior to Windows 2000, meaning that using them to check for Windows 2000 or later will always return true. Even if xoreos is running on Windows 9x or NT 4 though, the `APPDATA` and `USERPROFILE` environment variables will be unset, meaning that xoreos would simply use the current directory as a fallback.

COMMON: Remove unnecessary version check on Windows

---

src/graphics/aurora/animationthread.cpp
src/graphics/aurora/animationthread.h
src/graphics/aurora/modelnode.cpp
src/graphics/aurora/modelnode.h
src/graphics/aurora/skeletalanimation.cpp
src/graphics/aurora/skeletalanimation.h

This PR should fix a regression in the animation smoothness with VSync ON, while also retaining thready-safety and acceptable performance.
I also tried to implement the animation thread pool, but it did not give a noticeble performance boost while introducing it's own set of synchronization problems.

GRAPHICS: Fix animation smoothness, optimize animations

---

src/aurora/actionscript/array.cpp
src/aurora/actionscript/asbuffer.cpp
src/aurora/actionscript/avm.cpp
src/aurora/actionscript/avm.h
src/aurora/actionscript/function.cpp
src/aurora/actionscript/function.h
src/aurora/actionscript/variable.cpp

A new small ActionScript Update

ACTIONSCRIPT: Update

---

src/common/rules.mk
src/common/semaphore.cpp
src/common/semaphore.h
src/events/requests.cpp
src/events/requesttypes.h
src/events/rules.mk

This fixes deadlock with anti-aliasing enabled.

COMMON: Restore SDL based Semaphore class

---

src/engines/jade/creature.cpp
src/engines/jade/creature.h
src/engines/jade/gui/chargen/charactergeneration.cpp
src/engines/jade/gui/chargen/charactergeneration.h
src/engines/jade/gui/chargen/charactergenerationbase.cpp
src/engines/jade/gui/chargen/charactergenerationbase.h
src/engines/jade/gui/chargen/characterinfo.cpp
src/engines/jade/gui/chargen/characterinfo.h
src/engines/jade/gui/chargen/charactername.cpp
src/engines/jade/gui/chargen/charactername.h
src/engines/jade/gui/chargen/characterselection.cpp
src/engines/jade/gui/chargen/characterselection.h
src/engines/jade/gui/chargen/charactersummary.cpp
src/engines/jade/gui/chargen/charactersummary.h
src/engines/jade/gui/chargen/rules.mk
src/engines/jade/gui/gui.cpp
src/engines/jade/gui/main/main.cpp
src/engines/jade/module.cpp
src/engines/jade/module.h

This PR tries to implement as much as possible the Jade Empire character generation menu and generates the player character.

JADE: Character Generation

---

src/engines/kotor/script/function_tables.h
src/engines/kotor2/script/function_tables.h
src/engines/kotorbase/script/functions.h
src/engines/kotorbase/script/functions_object.cpp

The GetTag nwscript function implemented.

KOTORBASE: GetTag nwscript function

---

.travis.yml

After i realized, that travis now offers the possibility to build for arm, i added some extensions to the travis file to build all linux targets for arm64.

BUILD: Add arm64 build and exclude osx from it

---

src/aurora/actionscript/asbuffer.cpp
src/aurora/actionscript/asbuffer.h
src/aurora/actionscript/avm.cpp
src/aurora/actionscript/avm.h
src/aurora/actionscript/avm_interval.cpp
src/aurora/actionscript/rules.mk
src/engines/eclipse/externalhandler.cpp
src/engines/eclipse/externalhandler.h
src/engines/eclipse/rules.mk
src/engines/rules.mk

This PR enables time and interval handling in the actionscript engine with an abstract interface and implements this in the newly introduces eclipse engine.

ACTIONSCRIPT: Time and interval handling

---

CMakeLists.txt
configure.ac
src/aurora/gff3writer.cpp
src/aurora/gff3writer.h
src/aurora/gfxfile.cpp
src/aurora/gfxfile.h
src/aurora/gr2file.cpp
src/aurora/gr2file.h
src/common/serializationstream.cpp
src/common/string.h
src/graphics/aurora/model_nwn.cpp
src/sound/fmodeventfile.h

Switches to C++17 and replaces some related boost-using code with std-using code.

BUILD: Switch to C++17
